curl -v \
 -X POST \
 -H "Accept: application/json" \
 -H "Content-Type: application/json" \
 -d '{"query":"mutation wishlist {removeWishlist(location_id: \"12340\",
 user_id: \"exampleid\") {on_wishlist}}"}' \
 http://localhost:3000/api/graphql